
package th.asset.webservicedetailassetservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetAssetDetail", targetNamespace = "http://Asset.th/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetAssetDetail {


    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetGunBrandResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetGunBrand")
    @WebResult(name = "GetLostAssetGunBrandResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetGunBrandResponse getLostAssetGunBrand(
        @WebParam(name = "GetLostAssetGunBrand", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetGunBrand parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetElecBrandResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetElecBrand")
    @WebResult(name = "GetLostAssetElecBrandResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetElecBrandResponse getLostAssetElecBrand(
        @WebParam(name = "GetLostAssetElecBrand", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetElecBrand parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetGunDetailResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetGunDetail")
    @WebResult(name = "GetLostAssetGunDetailResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetGunDetailResponse getLostAssetGunDetail(
        @WebParam(name = "GetLostAssetGunDetail", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetGunDetail parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetElecCharacterResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetElecCharacter")
    @WebResult(name = "GetLostAssetElecCharacterResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetElecCharacterResponse getLostAssetElecCharacter(
        @WebParam(name = "GetLostAssetElecCharacter", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetElecCharacter parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetUnknowsDetailResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetUnknowsDetail")
    @WebResult(name = "GetLostAssetUnknowsDetailResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetUnknowsDetailResponse getLostAssetUnknowsDetail(
        @WebParam(name = "GetLostAssetUnknowsDetail", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetUnknowsDetail parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetAccessoriesResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetAccessories")
    @WebResult(name = "GetLostAssetAccessoriesResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetAccessoriesResponse getLostAssetAccessories(
        @WebParam(name = "GetLostAssetAccessories", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetAccessories parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetGunResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetGun")
    @WebResult(name = "GetLostAssetGunResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetGunResponse getLostAssetGun(
        @WebParam(name = "GetLostAssetGun", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetGun parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetUnknowsResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetUnknows")
    @WebResult(name = "GetLostAssetUnknowsResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetUnknowsResponse getLostAssetUnknows(
        @WebParam(name = "GetLostAssetUnknows", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetUnknows parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetAccessoriesDetailResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetAccessoriesDetail")
    @WebResult(name = "GetLostAssetAccessoriesDetailResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetAccessoriesDetailResponse getLostAssetAccessoriesDetail(
        @WebParam(name = "GetLostAssetAccessoriesDetail", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetAccessoriesDetail parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.asset.webservicedetailassetservice.GetLostAssetElecResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetElec")
    @WebResult(name = "GetLostAssetElecResponse", targetNamespace = "http://Asset.th/", partName = "parameters")
    public GetLostAssetElecResponse getLostAssetElec(
        @WebParam(name = "GetLostAssetElec", targetNamespace = "http://Asset.th/", partName = "parameters")
        GetLostAssetElec parameters)
        throws SQLException_Exception
    ;

}
