
package th.weapon.webservicelistweaponservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceListWeaponService", targetNamespace = "http://Weapon.th/", wsdlLocation = "WebServiceListWeaponService.wsdl")
public class WebServiceListWeaponServiceClient
    extends Service
{

    private final static URL WEBSERVICELISTWEAPONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(th.weapon.webservicelistweaponservice.WebServiceListWeaponServiceClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = th.weapon.webservicelistweaponservice.WebServiceListWeaponServiceClient.class.getResource(".");
            url = new URL(baseUrl, "WebServiceListWeaponService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WebServiceListWeaponService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICELISTWEAPONSERVICE_WSDL_LOCATION = url;
    }

    public WebServiceListWeaponServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceListWeaponServiceClient() {
        super(WEBSERVICELISTWEAPONSERVICE_WSDL_LOCATION, new QName("http://Weapon.th/", "WebServiceListWeaponService"));
    }

    /**
     * 
     * @return
     *     returns GetWeaponList
     */
    @WebEndpoint(name = "WebServiceListWeaponPort")
    public GetWeaponList getWebServiceListWeaponPort() {
        return super.getPort(new QName("http://Weapon.th/", "WebServiceListWeaponPort"), GetWeaponList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetWeaponList
     */
    @WebEndpoint(name = "WebServiceListWeaponPort")
    public GetWeaponList getWebServiceListWeaponPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Weapon.th/", "WebServiceListWeaponPort"), GetWeaponList.class, features);
    }

}
