
package th.vehicles.webservicelistvehicleservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceListVehicleService", targetNamespace = "http://vehicles.th/", wsdlLocation = "WebServiceListVehicleService.wsdl")
public class WebServiceListVehicleServiceClient
    extends Service
{

    private final static URL WEBSERVICELISTVEHICLESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(th.vehicles.webservicelistvehicleservice.WebServiceListVehicleServiceClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = th.vehicles.webservicelistvehicleservice.WebServiceListVehicleServiceClient.class.getResource(".");
            url = new URL(baseUrl, "WebServiceListVehicleService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WebServiceListVehicleService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICELISTVEHICLESERVICE_WSDL_LOCATION = url;
    }

    public WebServiceListVehicleServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceListVehicleServiceClient() {
        super(WEBSERVICELISTVEHICLESERVICE_WSDL_LOCATION, new QName("http://vehicles.th/", "WebServiceListVehicleService"));
    }

    /**
     * 
     * @return
     *     returns GetVehicleList
     */
    @WebEndpoint(name = "WebServiceListVehiclePort")
    public GetVehicleList getWebServiceListVehiclePort() {
        return super.getPort(new QName("http://vehicles.th/", "WebServiceListVehiclePort"), GetVehicleList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetVehicleList
     */
    @WebEndpoint(name = "WebServiceListVehiclePort")
    public GetVehicleList getWebServiceListVehiclePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://vehicles.th/", "WebServiceListVehiclePort"), GetVehicleList.class, features);
    }

}
