
package th.lawsuit.webservicelistlawsuitservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetLawsuitList", targetNamespace = "http://Lawsuit.th/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetLawsuitList {


    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetLostManListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostManList")
    @WebResult(name = "GetLostManListResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetLostManListResponse getLostManList(
        @WebParam(name = "GetLostManList", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetLostManList parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetPlanHisListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPlanHisList")
    @WebResult(name = "GetPlanHisListResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetPlanHisListResponse getPlanHisList(
        @WebParam(name = "GetPlanHisList", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetPlanHisList parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetLostCarListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostCarList")
    @WebResult(name = "GetLostCarListResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetLostCarListResponse getLostCarList(
        @WebParam(name = "GetLostCarList", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetLostCarList parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetWanHisListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisList")
    @WebResult(name = "GetWanHisListResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisListResponse getWanHisList(
        @WebParam(name = "GetWanHisList", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisList parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetWanHisListCrimeResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisListCrime")
    @WebResult(name = "GetWanHisListCrimeResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisListCrimeResponse getWanHisListCrime(
        @WebParam(name = "GetWanHisListCrime", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisListCrime parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetCrimeListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrimeList")
    @WebResult(name = "GetCrimeListResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetCrimeListResponse getCrimeList(
        @WebParam(name = "GetCrimeList", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetCrimeList parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetCrimeListOtherResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrimeListOther")
    @WebResult(name = "GetCrimeListOtherResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetCrimeListOtherResponse getCrimeListOther(
        @WebParam(name = "GetCrimeListOther", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetCrimeListOther parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetOjHisListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetOjHisList")
    @WebResult(name = "GetOjHisListResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetOjHisListResponse getOjHisList(
        @WebParam(name = "GetOjHisList", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetOjHisList parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetLostCarListCrimeResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostCarListCrime")
    @WebResult(name = "GetLostCarListCrimeResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetLostCarListCrimeResponse getLostCarListCrime(
        @WebParam(name = "GetLostCarListCrime", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetLostCarListCrime parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetLostAssetListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetList")
    @WebResult(name = "GetLostAssetListResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetLostAssetListResponse getLostAssetList(
        @WebParam(name = "GetLostAssetList", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetLostAssetList parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicelistlawsuitservice.GetWanHisListTrafResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisListTraf")
    @WebResult(name = "GetWanHisListTrafResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisListTrafResponse getWanHisListTraf(
        @WebParam(name = "GetWanHisListTraf", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisListTraf parameters)
        throws SQLException_Exception
    ;

}
