
package th.lawsuit.webservicelistlawsuitservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceListLawsuitService", targetNamespace = "http://Lawsuit.th/", wsdlLocation = "WebServiceListLawsuitService.wsdl")
public class WebServiceListLawsuitServiceClient
    extends Service
{

    private final static URL WEBSERVICELISTLAWSUITSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(th.lawsuit.webservicelistlawsuitservice.WebServiceListLawsuitServiceClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = th.lawsuit.webservicelistlawsuitservice.WebServiceListLawsuitServiceClient.class.getResource(".");
            url = new URL(baseUrl, "WebServiceListLawsuitService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WebServiceListLawsuitService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICELISTLAWSUITSERVICE_WSDL_LOCATION = url;
    }

    public WebServiceListLawsuitServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceListLawsuitServiceClient() {
        super(WEBSERVICELISTLAWSUITSERVICE_WSDL_LOCATION, new QName("http://Lawsuit.th/", "WebServiceListLawsuitService"));
    }

    /**
     * 
     * @return
     *     returns GetLawsuitList
     */
    @WebEndpoint(name = "WebServiceListLawsuitPort")
    public GetLawsuitList getWebServiceListLawsuitPort() {
        return super.getPort(new QName("http://Lawsuit.th/", "WebServiceListLawsuitPort"), GetLawsuitList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetLawsuitList
     */
    @WebEndpoint(name = "WebServiceListLawsuitPort")
    public GetLawsuitList getWebServiceListLawsuitPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Lawsuit.th/", "WebServiceListLawsuitPort"), GetLawsuitList.class, features);
    }

}
