
package th.location.webservicelistlocationservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetLocationList", targetNamespace = "http://Location.th/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetLocationList {


    /**
     * 
     * @param parameters
     * @return
     *     returns th.location.webservicelistlocationservice.GetPersonListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPersonList")
    @WebResult(name = "GetPersonListResponse", targetNamespace = "http://Location.th/", partName = "parameters")
    public GetPersonListResponse getPersonList(
        @WebParam(name = "GetPersonList", targetNamespace = "http://Location.th/", partName = "parameters")
        GetPersonList parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.location.webservicelistlocationservice.GetPlaceListResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPlaceList")
    @WebResult(name = "GetPlaceListResponse", targetNamespace = "http://Location.th/", partName = "parameters")
    public GetPlaceListResponse getPlaceList(
        @WebParam(name = "GetPlaceList", targetNamespace = "http://Location.th/", partName = "parameters")
        GetPlaceList parameters)
        throws SQLException_Exception
    ;

}
