
package th.location.webservicelistlocationservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceListLocationService", targetNamespace = "http://Location.th/", wsdlLocation = "WebServiceListLocationService.wsdl")
public class WebServiceListLocationServiceClient
    extends Service
{

    private final static URL WEBSERVICELISTLOCATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(th.location.webservicelistlocationservice.WebServiceListLocationServiceClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = th.location.webservicelistlocationservice.WebServiceListLocationServiceClient.class.getResource(".");
            url = new URL(baseUrl, "WebServiceListLocationService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WebServiceListLocationService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICELISTLOCATIONSERVICE_WSDL_LOCATION = url;
    }

    public WebServiceListLocationServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceListLocationServiceClient() {
        super(WEBSERVICELISTLOCATIONSERVICE_WSDL_LOCATION, new QName("http://Location.th/", "WebServiceListLocationService"));
    }

    /**
     * 
     * @return
     *     returns GetLocationList
     */
    @WebEndpoint(name = "WebServiceListLocationPort")
    public GetLocationList getWebServiceListLocationPort() {
        return super.getPort(new QName("http://Location.th/", "WebServiceListLocationPort"), GetLocationList.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetLocationList
     */
    @WebEndpoint(name = "WebServiceListLocationPort")
    public GetLocationList getWebServiceListLocationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Location.th/", "WebServiceListLocationPort"), GetLocationList.class, features);
    }

}
