
package th.weapon.webservicedetailweapon;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceDetailWeaponPortType", targetNamespace = "http://Weapon.th/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceDetailWeaponPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetCrimeGunOwnerResponse
     * @throws SQLException_Exception
     */
    @WebMethod
    @WebResult(name = "getCrimeGunOwnerResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetCrimeGunOwnerResponse getCrimeGunOwner(
        @WebParam(name = "getCrimeGunOwner", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetCrimeGunOwner parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetCrimeGunResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrimeGun")
    @WebResult(name = "GetCrimeGunResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetCrimeGunResponse getCrimeGun(
        @WebParam(name = "GetCrimeGun", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetCrimeGun parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetLostAssetResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAsset")
    @WebResult(name = "GetLostAssetResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetLostAssetResponse getLostAsset(
        @WebParam(name = "GetLostAsset", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetLostAsset parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetCrimeResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrime")
    @WebResult(name = "GetCrimeResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetCrimeResponse getCrime(
        @WebParam(name = "GetCrime", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetCrime parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetCrimeOwnerResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrimeOwner")
    @WebResult(name = "GetCrimeOwnerResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetCrimeOwnerResponse getCrimeOwner(
        @WebParam(name = "GetCrimeOwner", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetCrimeOwner parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetPersonResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPerson")
    @WebResult(name = "GetPersonResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetPersonResponse getPerson(
        @WebParam(name = "GetPerson", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetPerson parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetLostAsset2Response
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAsset2")
    @WebResult(name = "GetLostAsset2Response", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetLostAsset2Response getLostAsset2(
        @WebParam(name = "GetLostAsset2", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetLostAsset2 parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetLostAssetMakerResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetMaker")
    @WebResult(name = "GetLostAssetMakerResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetLostAssetMakerResponse getLostAssetMaker(
        @WebParam(name = "GetLostAssetMaker", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetLostAssetMaker parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetPlanHisHowResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPlanHisHow")
    @WebResult(name = "GetPlanHisHowResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetPlanHisHowResponse getPlanHisHow(
        @WebParam(name = "GetPlanHisHow", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetPlanHisHow parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetPlanHisResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPlanHis")
    @WebResult(name = "GetPlanHisResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetPlanHisResponse getPlanHis(
        @WebParam(name = "GetPlanHis", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetPlanHis parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.weapon.webservicedetailweapon.GetLostAssetBrandResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetBrand")
    @WebResult(name = "GetLostAssetBrandResponse", targetNamespace = "http://Weapon.th/", partName = "parameters")
    public GetLostAssetBrandResponse getLostAssetBrand(
        @WebParam(name = "GetLostAssetBrand", targetNamespace = "http://Weapon.th/", partName = "parameters")
        GetLostAssetBrand parameters)
        throws SQLException_Exception
    ;

}
