
package th.weapon.webservicedetailweapon;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceDetailWeapon", targetNamespace = "http://Weapon.th/", wsdlLocation = "WebServiceDetailWeapon.wsdl")
public class WebServiceDetailWeaponClient
    extends Service
{

    private final static URL WEBSERVICEDETAILWEAPON_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(th.weapon.webservicedetailweapon.WebServiceDetailWeaponClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = th.weapon.webservicedetailweapon.WebServiceDetailWeaponClient.class.getResource(".");
            url = new URL(baseUrl, "WebServiceDetailWeapon.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WebServiceDetailWeapon.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICEDETAILWEAPON_WSDL_LOCATION = url;
    }

    public WebServiceDetailWeaponClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceDetailWeaponClient() {
        super(WEBSERVICEDETAILWEAPON_WSDL_LOCATION, new QName("http://Weapon.th/", "WebServiceDetailWeapon"));
    }

    /**
     * 
     * @return
     *     returns WebServiceDetailWeaponPortType
     */
    @WebEndpoint(name = "WebServiceDetailWeaponPort")
    public WebServiceDetailWeaponPortType getWebServiceDetailWeaponPort() {
        return super.getPort(new QName("http://Weapon.th/", "WebServiceDetailWeaponPort"), WebServiceDetailWeaponPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceDetailWeaponPortType
     */
    @WebEndpoint(name = "WebServiceDetailWeaponPort")
    public WebServiceDetailWeaponPortType getWebServiceDetailWeaponPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Weapon.th/", "WebServiceDetailWeaponPort"), WebServiceDetailWeaponPortType.class, features);
    }

}
