
package th.lawsuit.webservicedetaillawsuitservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetLawsuitDetail", targetNamespace = "http://Lawsuit.th/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetLawsuitDetail {


    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetPlanHisResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPlanHis")
    @WebResult(name = "GetPlanHisResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetPlanHisResponse getPlanHis(
        @WebParam(name = "GetPlanHis", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetPlanHis parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetCrimeOtherResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrimeOther")
    @WebResult(name = "GetCrimeOtherResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetCrimeOtherResponse getCrimeOther(
        @WebParam(name = "GetCrimeOther", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetCrimeOther parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetWanHisProvResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisProv")
    @WebResult(name = "GetWanHisProvResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisProvResponse getWanHisProv(
        @WebParam(name = "GetWanHisProv", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisProv parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetWanHisDownloadResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisDownload")
    @WebResult(name = "GetWanHisDownloadResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisDownloadResponse getWanHisDownload(
        @WebParam(name = "GetWanHisDownload", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisDownload parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetLostManResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostMan")
    @WebResult(name = "GetLostManResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetLostManResponse getLostMan(
        @WebParam(name = "GetLostMan", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetLostMan parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetOjHisResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetOjHis")
    @WebResult(name = "GetOjHisResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetOjHisResponse getOjHis(
        @WebParam(name = "GetOjHis", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetOjHis parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetCarLostResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCarLost")
    @WebResult(name = "GetCarLostResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetCarLostResponse getCarLost(
        @WebParam(name = "GetCarLost", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetCarLost parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetCrimeOffenderResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrimeOffender")
    @WebResult(name = "GetCrimeOffenderResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetCrimeOffenderResponse getCrimeOffender(
        @WebParam(name = "GetCrimeOffender", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetCrimeOffender parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetPlanHisSpouseResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPlanHisSpouse")
    @WebResult(name = "GetPlanHisSpouseResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetPlanHisSpouseResponse getPlanHisSpouse(
        @WebParam(name = "GetPlanHisSpouse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetPlanHisSpouse parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetWanHisTrafficResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisTraffic")
    @WebResult(name = "GetWanHisTrafficResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisTrafficResponse getWanHisTraffic(
        @WebParam(name = "GetWanHisTraffic", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisTraffic parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetPlanHisNameResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPlanHisName")
    @WebResult(name = "GetPlanHisNameResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetPlanHisNameResponse getPlanHisName(
        @WebParam(name = "GetPlanHisName", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetPlanHisName parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetLostCarCrimeResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostCarCrime")
    @WebResult(name = "GetLostCarCrimeResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetLostCarCrimeResponse getLostCarCrime(
        @WebParam(name = "GetLostCarCrime", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetLostCarCrime parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetCrimeResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrime")
    @WebResult(name = "GetCrimeResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetCrimeResponse getCrime(
        @WebParam(name = "GetCrime", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetCrime parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetOjHisJudgmentsResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetOjHisJudgments")
    @WebResult(name = "GetOjHisJudgmentsResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetOjHisJudgmentsResponse getOjHisJudgments(
        @WebParam(name = "GetOjHisJudgments", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetOjHisJudgments parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetWanHisDownloadTrafResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisDownloadTraf")
    @WebResult(name = "GetWanHisDownloadTrafResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisDownloadTrafResponse getWanHisDownloadTraf(
        @WebParam(name = "GetWanHisDownloadTraf", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisDownloadTraf parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetCrimeComplainantResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrimeComplainant")
    @WebResult(name = "GetCrimeComplainantResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetCrimeComplainantResponse getCrimeComplainant(
        @WebParam(name = "GetCrimeComplainant", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetCrimeComplainant parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetLostAssetResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAsset")
    @WebResult(name = "GetLostAssetResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetLostAssetResponse getLostAsset(
        @WebParam(name = "GetLostAsset", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetLostAsset parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetWanHisCrimeResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisCrime")
    @WebResult(name = "GetWanHisCrimeResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisCrimeResponse getWanHisCrime(
        @WebParam(name = "GetWanHisCrime", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisCrime parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetWanHisProvinceResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisProvince")
    @WebResult(name = "GetWanHisProvinceResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisProvinceResponse getWanHisProvince(
        @WebParam(name = "GetWanHisProvince", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisProvince parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetCarLostColorResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCarLostColor")
    @WebResult(name = "GetCarLostColorResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetCarLostColorResponse getCarLostColor(
        @WebParam(name = "GetCarLostColor", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetCarLostColor parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetWanHisEducationResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisEducation")
    @WebResult(name = "GetWanHisEducationResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisEducationResponse getWanHisEducation(
        @WebParam(name = "GetWanHisEducation", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisEducation parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetOjHisAcquittedResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetOjHisAcquitted")
    @WebResult(name = "GetOjHisAcquittedResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetOjHisAcquittedResponse getOjHisAcquitted(
        @WebParam(name = "GetOjHisAcquitted", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetOjHisAcquitted parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetLostAssetDetailResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostAssetDetail")
    @WebResult(name = "GetLostAssetDetailResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetLostAssetDetailResponse getLostAssetDetail(
        @WebParam(name = "GetLostAssetDetail", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetLostAssetDetail parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetPlanHisOtherNameResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPlanHisOtherName")
    @WebResult(name = "GetPlanHisOtherNameResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetPlanHisOtherNameResponse getPlanHisOtherName(
        @WebParam(name = "GetPlanHisOtherName", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetPlanHisOtherName parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.lawsuit.webservicedetaillawsuitservice.GetWanHisEducateStatusResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetWanHisEducateStatus")
    @WebResult(name = "GetWanHisEducateStatusResponse", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
    public GetWanHisEducateStatusResponse getWanHisEducateStatus(
        @WebParam(name = "GetWanHisEducateStatus", targetNamespace = "http://Lawsuit.th/", partName = "parameters")
        GetWanHisEducateStatus parameters)
        throws SQLException_Exception
    ;

}
