
package th.vehicles.webservicedetailvehicleservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetVehicleDetail", targetNamespace = "http://vehicles.th/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetVehicleDetail {


    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetCarByKeyResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCarByKey")
    @WebResult(name = "GetCarByKeyResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetCarByKeyResponse getCarByKey(
        @WebParam(name = "GetCarByKey", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetCarByKey parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetCrimeEXTResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrimeEXT")
    @WebResult(name = "GetCrimeEXTResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetCrimeEXTResponse getCrimeEXT(
        @WebParam(name = "GetCrimeEXT", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetCrimeEXT parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetAccNationResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetAccNation")
    @WebResult(name = "GetAccNationResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetAccNationResponse getAccNation(
        @WebParam(name = "GetAccNation", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetAccNation parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetLostCarResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostCar")
    @WebResult(name = "GetLostCarResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetLostCarResponse getLostCar(
        @WebParam(name = "GetLostCar", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetLostCar parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetAccidentCarResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetAccidentCar")
    @WebResult(name = "GetAccidentCarResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetAccidentCarResponse getAccidentCar(
        @WebParam(name = "GetAccidentCar", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetAccidentCar parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetLostCarPenaltyResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostCarPenalty")
    @WebResult(name = "GetLostCarPenaltyResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetLostCarPenaltyResponse getLostCarPenalty(
        @WebParam(name = "GetLostCarPenalty", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetLostCarPenalty parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetTrcByKeyColorResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetTrcByKeyColor")
    @WebResult(name = "GetTrcByKeyColorResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetTrcByKeyColorResponse getTrcByKeyColor(
        @WebParam(name = "GetTrcByKeyColor", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetTrcByKeyColor parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetTicketsResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetTickets")
    @WebResult(name = "GetTicketsResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetTicketsResponse getTickets(
        @WebParam(name = "GetTickets", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetTickets parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetPersonCRIMEResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPersonCRIME")
    @WebResult(name = "GetPersonCRIMEResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetPersonCRIMEResponse getPersonCRIME(
        @WebParam(name = "GetPersonCRIME", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetPersonCRIME parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetPersonResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPerson")
    @WebResult(name = "GetPersonResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetPersonResponse getPerson(
        @WebParam(name = "GetPerson", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetPerson parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetInterceptResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetIntercept")
    @WebResult(name = "GetInterceptResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetInterceptResponse getIntercept(
        @WebParam(name = "GetIntercept", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetIntercept parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetCrimeResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCrime")
    @WebResult(name = "GetCrimeResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetCrimeResponse getCrime(
        @WebParam(name = "GetCrime", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetCrime parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetTrcByKeyResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetTrcByKey")
    @WebResult(name = "GetTrcByKeyResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetTrcByKeyResponse getTrcByKey(
        @WebParam(name = "GetTrcByKey", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetTrcByKey parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetCarByKeyColorResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetCarByKeyColor")
    @WebResult(name = "GetCarByKeyColorResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetCarByKeyColorResponse getCarByKeyColor(
        @WebParam(name = "GetCarByKeyColor", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetCarByKeyColor parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetConfiscateResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetConfiscate")
    @WebResult(name = "GetConfiscateResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetConfiscateResponse getConfiscate(
        @WebParam(name = "GetConfiscate", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetConfiscate parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetTicketMBVResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetTicketMBV")
    @WebResult(name = "GetTicketMBVResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetTicketMBVResponse getTicketMBV(
        @WebParam(name = "GetTicketMBV", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetTicketMBV parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetPersonVEHICLEResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetPersonVEHICLE")
    @WebResult(name = "GetPersonVEHICLEResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetPersonVEHICLEResponse getPersonVEHICLE(
        @WebParam(name = "GetPersonVEHICLE", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetPersonVEHICLE parameters)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns th.vehicles.webservicedetailvehicleservice.GetLostCarColorResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetLostCarColor")
    @WebResult(name = "GetLostCarColorResponse", targetNamespace = "http://vehicles.th/", partName = "parameters")
    public GetLostCarColorResponse getLostCarColor(
        @WebParam(name = "GetLostCarColor", targetNamespace = "http://vehicles.th/", partName = "parameters")
        GetLostCarColor parameters)
        throws SQLException_Exception
    ;

}
