
package th.vehicles.webservicedetailvehicleservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceDetailVehicleService", targetNamespace = "http://vehicles.th/", wsdlLocation = "WebServiceDetailVehicleService.wsdl")
public class WebServiceDetailVehicleServiceClient
    extends Service
{

    private final static URL WEBSERVICEDETAILVEHICLESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(th.vehicles.webservicedetailvehicleservice.WebServiceDetailVehicleServiceClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = th.vehicles.webservicedetailvehicleservice.WebServiceDetailVehicleServiceClient.class.getResource(".");
            url = new URL(baseUrl, "WebServiceDetailVehicleService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'WebServiceDetailVehicleService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICEDETAILVEHICLESERVICE_WSDL_LOCATION = url;
    }

    public WebServiceDetailVehicleServiceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceDetailVehicleServiceClient() {
        super(WEBSERVICEDETAILVEHICLESERVICE_WSDL_LOCATION, new QName("http://vehicles.th/", "WebServiceDetailVehicleService"));
    }

    /**
     * 
     * @return
     *     returns GetVehicleDetail
     */
    @WebEndpoint(name = "WebServiceDetailVehiclePort")
    public GetVehicleDetail getWebServiceDetailVehiclePort() {
        return super.getPort(new QName("http://vehicles.th/", "WebServiceDetailVehiclePort"), GetVehicleDetail.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetVehicleDetail
     */
    @WebEndpoint(name = "WebServiceDetailVehiclePort")
    public GetVehicleDetail getWebServiceDetailVehiclePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://vehicles.th/", "WebServiceDetailVehiclePort"), GetVehicleDetail.class, features);
    }

}
